language: java
jdk:
  - oraclejdk8

services:
  - mysql

before_install:
  - sudo chmod +x ./config_services.sh
  - ./config_services.sh

install: true

script:
  - sudo chmod +x ./run_build.sh
  - travis_wait ./run_build.sh
  - sudo chmod +x ./performance_test.sh
  - ./performance_test.sh
  - cat ./platform/mds/mds-performance-tests/target/performanceTestResult.log

cache:
  directories:
    - $HOME/.m2

notifications:
  email:
    recipients:
      - travis-test-maniek@googlegroups.com
    on_success: never
    on_failure: always
